// HEADS UP! THIS FILE IS AUTO-GENERATED BY THE 'test:build-karma-index' gulp task.

require( "./helpers/phantomjs-shims.js" );
require( "./helpers/setup.js" );
require( "./components/ElijahManor.spec.jsx" );
require( "./stores/fatherStore.spec.js" );